exports.EXPIRE_SESSION = 3600000;
exports.SERVER_PORT = 5002;
exports.SERVER_ADDRESS = "localhost:5002";
exports.SECRET_SESSION = "UhWt34^fjEe9UWfh$9JxH*r$qSYKyeT=t=58ypkx#uKAtUack-WsLW8248ckh_Bkn";
exports.DATABASE_NAME = "ablog";
exports.DATABASE_ADDRESS = "localhost:27017";
exports.DEFAULT_AVATAR = "user.png";
exports.DEFAULT_ARTICLE_IMAGE = "article.png";
exports.EDITOR_IMAGE_PATH = "../public/assets/articles/";